import React from 'react'

export default function About() {
  return (
    <div>
      <h3>Hello Everyone</h3>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure mollitia nesciunt ipsa vitae corrupti officiis velit rem impedit, suscipit, ea possimus veniam, distinctio id necessitatibus sit quam asperiores quas cumque! Iste eveniet ducimus corrupti optio velit? Recusandae, sed a voluptates minima ipsa corporis explicabo harum, similique molestiae accusamus atque repudiandae quis! Culpa veritatis doloribus quia amet consequatur modi enim fugit, commodi quae fugiat, provident magni inventore iure minima sapiente repellat ea mollitia labore eligendi animi? Minus, vero. Omnis, facilis? Laboriosam quo fugit dolores perferendis modi dolor nobis a, ex commodi. Unde temporibus provident quam, quas eius qui beatae, dolorum itaque eos reprehenderit tempore odio ex iusto quo veniam maxime cupiditate quae explicabo? Architecto maiores quasi vel excepturi fugit quod assumenda numquam, similique temporibus! Exercitationem nam nobis commodi unde aperiam temporibus nesciunt obcaecati at, nisi reprehenderit odio id amet voluptate asperiores tenetur eaque numquam illum ex facere velit culpa quaerat iste. Provident reprehenderit quasi sit nisi, autem cupiditate laborum pariatur? Ipsa, similique earum! Facilis quam in blanditiis? Officia, impedit eaque. Similique repellendus expedita obcaecati voluptates quos velit optio accusantium autem consequuntur fugiat mollitia incidunt praesentium tempora repudiandae fuga veniam, iste esse blanditiis doloribus laudantium perferendis consectetur saepe, doloremque magnam! Unde inventore soluta nobis reiciendis quaerat nam assumenda nostrum saepe totam voluptate eius maiores voluptatibus, sequi sint facere animi possimus voluptates expedita fuga architecto pariatur, voluptatem recusandae aperiam dolorem. Et nostrum ad at, iusto voluptas dicta, voluptatum architecto dolorem facilis corrupti iure repellendus nisi rerum earum nesciunt unde soluta consectetur error perspiciatis? Voluptates repellat voluptatum, tenetur vel, facilis sapiente id dicta labore aliquid laudantium hic quibusdam illo sint distinctio mollitia. Impedit, at? Veniam non harum similique facilis nisi quo officiis excepturi perspiciatis, rem hic culpa. Atque consectetur provident incidunt, praesentium aliquid, blanditiis omnis architecto odit, ut unde voluptatibus cum exercitationem laborum harum?</p>
    </div>
  )
}
